name: Update

on:
  workflow_dispatch: {}
  schedule:
    - cron: "22 11 * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - run: nix flake update --commit-lock-file
      - id: nix-flake-changelog
        run: |
          delimiter="$(openssl rand -hex 16)"
          echo "message<<${delimiter}" >> "${GITHUB_OUTPUT}"
          git log -1 --pretty=%B | tail +3 | nix run github:iff/flakers >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      - run: nix develop -c -- scripts/refresh-readme.sh

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: update
          title: Update
          body: "${{ steps.nix-flake-changelog.outputs.message }}"
